# site properties and page defaults
title: EcoEvoGenomics
subtitle: The Ecological and Evolutionary Genetics Group at the University of Oslo
description: Welcome to the EEG group at UiO. We are interested in understanding the basis of adaptation and speciation and also how human activity shapes and alters these processes!
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: mark.ravinet@ibv.uio.no
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: markravinet
  twitter: markravinet
  youtube: markravinet

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
